# https://qiita.com/jhorikawa_err/items/fb9c03c0982c29c5b6d5
# $ pip install -r requirements.txt

# ベースイメージ
FROM python:3.9.0

# pipをアップグレード
RUN pip install --upgrade pip

# 作業ディレクトリ作成
WORKDIR /workdir

# ポート
EXPOSE 8080
